import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/setup")({
  head: () => ({
    meta: [
      { title: "PC Setup — Mobile Rig Virtual Controller" },
      {
        name: "description",
        content:
          "Step-by-step guide to pair your phone's virtual wheel and joystick with any PC game using the Mobile Rig bridge.",
      },
      { property: "og:title", content: "PC Setup — Mobile Rig" },
      {
        property: "og:description",
        content: "Install the bridge, start it, and your phone appears as a low-latency virtual game controller in Windows.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Setup,
});

const steps = [
  {
    t: "1. Install the driver",
    d: "On the PC, install the ViGEmBus virtual gamepad driver. The original project is retired, but its final Windows 10/11 installer is still available from the official Nefarius GitHub releases page.",
  },
  {
    t: "2. Install the C++ build tools",
    d: "Install Visual Studio Build Tools 2022 and select the Desktop development with C++ workload. The vigemclient package contains native C++ code and node-gyp needs a Visual C++ compiler to build it.",
  },
  {
    t: "3. Install Node.js",
    d: "Install Node.js 18 or newer. Your current Node.js 24 installation is okay; reopen the terminal after installing the C++ tools.",
  },
  {
    t: "4. Get the bridge",
    d: "Download rig-bridge.js below into an empty folder, open that folder in a terminal, and run: npm init -y && npm i ws vigemclient",
  },
  {
    t: "5. Start it",
    d: "Run: node rig-bridge.js. It listens for the phone on ws://<PC-IP>:8787 and also listens for live game telemetry on UDP 5300 (Forza Data Out) and UDP 20777 (EA F1 telemetry). Allow Node through the Windows firewall on private networks.",
  },
  {
    t: "6. Enable game telemetry",
    d: "Forza Horizon: enable Settings → HUD and Gameplay → Data Out, set the PC's IP address and UDP port 5300. For F1 25 / 2026 Season Pack: enable UDP Telemetry Output, set the PC's IP and UDP port 20777, and choose 60 Hz. The steering gauges stay at -- until real game telemetry arrives.",
  },
  {
    t: "7. Pair the phone",
    d: "Phone and PC must be on the same Wi-Fi. On the phone, open Setup and enter ws://<PC-IP>:8787, then tap Connect.",
  },
  {
    t: "8. Play",
    d: "Steering mode receives the game's real speed, RPM and gear packets through the bridge. No speed or RPM values are generated by the phone UI.",
  },
];

function Setup() {
  return (
    <main className="mx-auto min-h-screen max-w-2xl px-4 py-8">
      <Link to="/" className="text-xs font-semibold uppercase tracking-widest text-primary">
        ← Back to controller
      </Link>
      <h1 className="mt-4 text-3xl font-bold">Connect to your PC</h1>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
        A web page can't reach a game on its own, so a tiny helper runs on the PC and turns what your
        phone sends into a genuine virtual gamepad. Set it up once; after that it's just tap and play.
      </p>

      <ol className="mt-6 space-y-3">
        {steps.map((s) => (
          <li key={s.t} className="panel p-4">
            <h2 className="text-base font-bold">{s.t}</h2>
            <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{s.d}</p>
          </li>
        ))}
      </ol>

      <div className="mt-4 flex flex-wrap gap-3">
        <a
          href="https://github.com/nefarius/ViGEmBus/releases/latest"
          target="_blank"
          rel="noreferrer"
          className="inline-flex rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-bold uppercase tracking-widest text-white hover:bg-white/10"
        >
          Install ViGEmBus
        </a>
        <a
          href="https://visualstudio.microsoft.com/visual-cpp-build-tools/"
          target="_blank"
          rel="noreferrer"
          className="inline-flex rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-bold uppercase tracking-widest text-white hover:bg-white/10"
        >
          Install C++ Build Tools
        </a>
      </div>

      <button
        type="button"
        onClick={async () => {
          try {
            const response = await fetch("/bridge/rig-bridge.js", { cache: "no-store" });
            if (!response.ok) throw new Error("Bridge file unavailable");
            const source = await response.text();
            if (!source.includes("Mobile Rig -> PC low-latency bridge")) {
              throw new Error("Bridge file content was not returned");
            }

            const blob = new Blob([source], { type: "application/octet-stream" });
            const url = URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = url;
            link.download = "rig-bridge.js";
            document.body.appendChild(link);
            link.click();
            link.remove();
            window.setTimeout(() => URL.revokeObjectURL(url), 1000);
          } catch {
            window.open("/bridge/rig-bridge.js", "_blank", "noopener,noreferrer");
          }
        }}
        className="mt-6 inline-flex rounded-xl px-5 py-3 text-sm font-bold uppercase tracking-widest text-primary-foreground glow"
        style={{ background: "var(--gradient-primary)" }}
      >
        Download rig-bridge.js
      </button>

      <div className="panel mt-6 p-4">
        <h2 className="text-base font-bold">Live telemetry</h2>
        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
          The steering dashboard does not invent speed or RPM. The PC bridge parses the game's
          telemetry packets and immediately forwards the newest values to the phone. Forza Data Out
          and EA F1 UDP telemetry are supported by the bridge; other games need a compatible
          telemetry adapter because every game exposes its data differently.
        </p>
        <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
          Do not run another application on the same UDP port. Games that send UDP telemetry can
          usually be forwarded by SimHub to another free port when another telemetry application
          already owns the game's default port.
        </p>
      </div>

      <div className="panel mt-6 p-4">
        <h2 className="text-base font-bold">Compatibility</h2>
        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
          XInput is the default PC output and a DualShock 4 virtual output is available for games that expect PlayStation-style input. Custom keyboard bindings are still controlled by the game or a separate input mapper. No browser controller can guarantee a fixed 3 ms end-to-end latency or support every anti-cheat/protected input path; network, device refresh, browser scheduling, driver, and game polling all affect the final result.
        </p>
      </div>

      <div className="panel mt-6 p-4">
        <h2 className="text-base font-bold">If npm install fails with node-gyp</h2>
        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
          An error such as “could not use Visual Studio”, “Failure details: undefined”, or
          “Desktop development with C++” means the native C++ compiler is missing. Install the
          C++ Build Tools above, reopen Command Prompt, then run the install command again.
          If a previous failed install left a locked node_modules folder, close Node/VS Code and
          remove node_modules before retrying.
        </p>
      </div>

      <p className="mt-6 text-xs leading-relaxed text-muted-foreground">
        Games that only read keyboard input can still work: pair the virtual pad with a key-mapping
        tool such as Steam Input or reWASD. On macOS and Linux the bridge runs in echo mode only,
        since the virtual-pad driver is Windows-only.
      </p>
    </main>
  );
}
